### PR TITLE
Try building PyPy wheels on macOS

### PR DESCRIPTION
**Pull request by khaledhosny**

### CODE REVIEW

**Review by anthrotype — APPROVED** [review]
LGTM

So far I haven't bothered building pypy wheels for non-linux since it's relatively more niche, but if you use it we can add to the rest of the native wheels used by the pipeline

**Comment by khaledhosny** [comment]
It seems to currently require macos-10.15 image, which probably breaks building M1 wheels. I think I’ll remove the macos-10.15  commits, and just don’t blacklist it, so that it starts to build when building on macos-11 is supported.

> Warning: PyPy is currently unsupported when building on macOS 11. To build macOS PyPy wheels, build on an older OS, such as macOS 10.15. To silence this warning, deselect PyPy by adding "pp*-macosx*" to your CIBW_SKIP option.

**Comment by anthrotype** [comment]
try un-pin cibuildwheel so it installs the latest one available, maybe that's fixed already. 
We should add universal2 wheels for apple silicon. that's arguably more important than pypy for mac x64_86

**Comment by anthrotype** [comment]
i set up compreffor's ci recently among others, maybe you can use that as reference
https://github.com/googlefonts/compreffor/blob/main/.github/workflows/ci.yml

**Comment by khaledhosny** [comment]
OK, this builds now. I might give universal2 wheels a try, but I don’t have apple silicon to test locally so not a priority for now. I wanted to test PyPy compilation on a somewhat slow project, but it turned out to be slower than CPython.

**Comment by anthrotype** [comment]
> it turned out to be slower than CPython.

yeah, that's why I haven't bothered building those

**Comment by khaledhosny** [comment]
If PyPy wheels built locally I would not even have noticed they are missing here.

**Comment by anthrotype** [comment]
why did they fail to build locally?

**Comment by khaledhosny** [comment]
Some C++ header was not found, for some reason it needed `-stdlib=libc++` to be passed to the C++ compiler:
```
  gcc -pthread -arch x86_64 -DNDEBUG -O2 -fPIC -DCYTHON_TRACE_NOGIL=1 -I/venv-pypy/include -I/usr/local/Cellar/pypy3/7.3.7/libexec/include -c src/openstep_plist/parser.cpp -o build/temp.macosx-10.7-x86_64-3.7/src/openstep_plist/parser.o -std=c++11
  clang: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  src/openstep_plist/parser.cpp:717:10: fatal error: 'ios' file not found
  #include "ios"
           ^~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
```

**Pull request merged**
